-- State
insert into STATE (uf_id, name) VALUES
('AC', 'Acre'),
('AL', 'Alagoas'),
('AP', 'Amapa'),
('AM', 'Amazonas'),
('BA', 'Bahia'),
('CE', 'Ceara'),
('DF', 'Distrito Federal'),
('ES', 'Espirito Santo'),
('GO', 'Goias'),
('MA', 'Maranhao'),
('MT', 'Mato Grosso'),
('MS', 'Mato Grosso do Sul'),
('MG', 'Minas Gerais'),
('PA', 'Para'),
('PB', 'Paraiba'),
('PR', 'Parana'),
('PE', 'Pernambuco'),
('PI', 'Piaui'),
('RJ', 'Rio de Janeiro'),
('RN', 'Rio grande do Norte'),
('RS', 'Rio Grande do Sul'),
('RO', 'Rondonia'),
('RR', 'Roraima'),
('SC', 'Santa Catarina'),
('SE', 'Sergipe'),
('SP', 'Sao Paulo'),
('TO', 'Tocantins');

-- City
insert into CITY (city_id, name) VALUES
(1,	'Rio Branco'),
(2,	'Maceió' ),
(3,	'Macapá' ),
(4,	'Manaus'),
(5,	'Salvador'),
(6,	'Fortaleza'),
(7,	'Brasília'),
(8,	'Vitória'),
(9,	'Goiânia'),
(10, 'São Luís'),
(11, 'Cuiabá'),
(12, 'Campo Grande'),
(13, 'Belo Horizonte'),
(14, 'Belém'),
(15, 'João Pessoa'),
(16, 'Curitiba'),
(17, 'Recife'),
(18, 'Teresina'),
(19, 'Rio de Janeiro'),
(20, 'Natal'),
(21, 'Porto Alegre'),
(22, 'Porto Velho'),
(23, 'Boa Vista'),
(24, 'Florianópolis'),
(25, 'São Paulo'),
(26, 'Aracaju'), 
(27, 'Palmas'); 

-- Cards
insert into CARD (card_id, edition, name, is_foil, is_altered) VALUES
(1, 'lorwyn', 'goblin', FALSE, FALSE),
(2, 'lorwyn', 'goblin', TRUE, FALSE),
(3, 'lorwyn', 'goblin', FALSE, TRUE),
(4, 'lorwyn', 'goblin', TRUE, TRUE),
(5, 'lorwyn', 'elfo', FALSE, FALSE),
(6, 'lorwyn', 'elfo', TRUE, FALSE),
(7, 'lorwyn', 'elfo', FALSE, TRUE),
(8, 'lorwyn', 'elfo', TRUE, TRUE),
(9, 'lorwyn', 'soldado', FALSE, FALSE),
(10, 'lorwyn', 'soldado', TRUE, FALSE),
(11, 'lorwyn', 'soldado', FALSE, TRUE),
(12, 'lorwyn', 'soldado', TRUE, TRUE),
(13, 'lorwyn', 'tritao', FALSE, FALSE),
(14, 'lorwyn', 'tritao', TRUE, FALSE),
(15, 'lorwyn', 'tritao', FALSE, TRUE),
(16, 'lorwyn', 'zumbi', TRUE, TRUE),
(17, 'lorwyn', 'zumbi', FALSE, FALSE),
(18, 'lorwyn', 'zumbi', TRUE, FALSE),
(19, 'lorwyn', 'zumbi', FALSE, TRUE),
(20, 'lorwyn', 'zumbi', TRUE, TRUE);
