spring:
  profiles.active: development
  thymeleaf:
    prefix: classpath:/templates
  jackson:
    serialization.write-dates-as-timestamps: false
  jpa.properties.hibernate.default_schema: sed
  mvc:
    favicon:
      enabled: true
    locale: pt_BR
  multipart:
    maxFileSize: 1024KB
    maxRequestSize: 1024KB
server.error.whitelabel.enabled: false
---
spring:
  profiles: development
  thymeleaf:
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS SED
    platform: h2